name: MkDocs deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install mkdocs mkdocs-material

      - name: Build MkDocs
        run: mkdocs build

      - name: Upload site content
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./site

  deploy:
    needs: build-deploy
    runs-on: ubuntu-latest

    # 👉 LA PARTE CHE TI MANCAVA:
    environment:
      name: github-pages

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4